config/routes.rb
EbookRenamer::Application.routes.draw do
  root :to => "books#index"
  resources :books do 
    collection do 
      get 'page/:page', :action => :index
      get 'authors'
      get 'review'
      get 'runcheck'
      put :accept_proposed_changed
    end
  end
end

app/models/book.rb
class Book < ActiveRecord::Base
  include BookCleaner

  attr_accessible :author, :file_type, :fullpath, :title, :dead, :for_review

  validates :file_type, presence: true
  validates :fullpath, presence: true

  default_scope where(dead: false)
  scope :no_author, where('author IS NULL')
  scope :no_title, where('title is NULL')
  scope :cleaned, where('title IS NOT NULL').where('author IS NOT NULL')
  scope :last_updated, order('updated_at DESC').limit(1)
  scope :to_review, where(for_review: true)

  has_paper_trail

  # Should move this out
  def next
    Book.where("books.id > ?", self.id).order("books.id ASC").limit(1).first
  end

  # Should move this out
  def previous
    Book.where("books.id < ?", self.id).order("books.id DESC").limit(1).last
  end

  def mark_as_destroyed
    self.update_attributes(dead: true)
  end

  def self.all_authors
    Book.select('DISTINCT author').where('author IS NOT NULL').where('for_review IS NOT TRUE').order(:author).map(&:author)
  end

  def self.text_search(query)
    if query.present?
      where("title @@ :q or author @@ :q or fullpath @@ :q", q: query).order('id DESC')
    else
      no_title
    end
  end

  private
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  http_basic_authenticate_with :name => "books", :password => "books"
  def show
    @book = Book.find(params[:id])
    @fields = @book.best_guess_fields
  end

  def index
    @book_count = Book.count
    @books_without_authors = Book.no_author.count
    @books_without_titles = Book.no_title.count
    @last_updated_book = Book.last_updated.first
    if params[:status] == 'cleaned'
      @books = Book.cleaned.page(params[:page]).per(5)
    else
      @books = Book.text_search(params[:query]).page(params[:page]).per(5)
    end
  end

  def destroy
    book = Book.find(params[:id])
    next_book = book.next
    book.mark_as_destroyed
    redirect_to root_path
  end

  def update
    @book = Book.find params[:id]

    respond_to do |format|
      if @book.update_attributes(params[:book])
        format.html { redirect_to(@book, :notice => 'Book was successfully updated.') }
        format.json { respond_with_bip(@book) }
      else
        format.html { render :action => "edit" }
        format.json { respond_with_bip(@book) }
      end
    end
  end

  def authors
    respond_to do |format|
      format.json { render json: Book.all_authors }
    end
  end

  def review
    @books = Book.to_review.order(:updated_at).page(params[:page]).per(50)
    @book_count = Book.to_review.count
    logger.info params
    if params[:layout] == 'bulk'
      render :bulk
    end
  end

  def accept_proposed_changed
    Book.update_all({for_review:false}, {id: params[:book_ids]})
    redirect_to review_books_path layout: 'bulk'
  end

  def runcheck
    Book.delay.full_search(100)
    redirect_to :books, notice: "Books are being searched, my friend"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.haml
%h3{id: "#{book.id}"}
  %span.author #{book.author} 
  %span.separator -
  %span.title #{book.title}
  - if book.author && book.title
    = link_to "http://www.amazon.com/gp/search/ref=sr_adv_b/?search-alias=stripbooks&unfiltered=1&field-keywords=&field-author=#{book.author.gsub(/ /, '+')}&field-title=#{book.title.gsub(/ /, '+')}&field-isbn=&field-publisher=&node=&field-p_n_condition-type=&field-feature_browse-bin=&field-subject=&field-language=&field-dateop=&field-datemod=&field-dateyear=&sort=relevanceexprank&Adv-Srch-Books-Submit.x=-433&Adv-Srch-Books-Submit.y=-485", target: '_blank', class: 'btn' do
      %i.icon-book
      %i.icon-search
Best guess author or title:
%ul{class: "#{book.id}"}
  - fields.each do |f|
    %li
      %span.field= f
      = link_to 'author', 'Javascript: void(0);', class: 'field_link'
      |
      = link_to 'flip author', 'Javascript: void(0);', class: 'flipper_link', id: 'author'
      |
      = link_to 'title', 'Javascript: void(0);', class: 'field_link'
%table.table.table-bordered.table-hover{class: "#{book.id}"}
  %thead
    %tr
      %th Author
      %th Title
      %th File Name (toggle #{ link_to 'full path', 'Javascript: void(0);', class: 'name_toggle'} )
      %th File Type
      - if book.for_review
        %th Correct?

  %tbody
    %tr
      %td= best_in_place book, :author, :data => { field: book.author }
      %td= best_in_place book, :title, :data => { field: book.title }
      %td.path{:data => { fullpath: book.fullpath }}= book.partial_path
      %td= book.file_type
      - if book.for_review
        %td= best_in_place book, :for_review, :type => :checkbox, :collection => ["Looks good", "Not good"]
%p 
  Not a book?
  = link_to 'Delete', "#delete", data: {toggle: "modal"}
#delete.modal.small.hide.fade{"aria-hidden" => "true", "aria-labelledby" => "DeleteModal", :role => "dialog", :tabindex => "-1"}
  .modal-header
    %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
    %h3#myModalLabel Delete Confirmation
  .modal-body
    %p.error-text Are you sure you want to delete this book?
  .modal-footer
    %button.btn{"aria-hidden" => "true", "data-dismiss" => "modal"} Cancel
    = link_to book_path(book), method: :delete do
      %button.btn.btn-danger{"data-dismiss" => "modal"} Delete

app/views/books/bulk.html.haml
%h1 Welcome Ben!
- if @books.empty?
  Congratulations, you have no books to review!
  = form_tag runcheck_books_path, method: :get do
    = submit_tag "Run Check", class: 'btn', name: nil
- else
  You have #{@book_count} to review.
  %h2 Books!
  = link_to 'regular view', review_books_path
  |
  = link_to 'bulk view', { layout: 'bulk'}
  = form_tag accept_proposed_changed_books_path, method: :put do
    %table.table.table-bordered.table-hover.table-fixed-header.table-striped
      %thead.header
        %tr
          %th Correct?
          %th Author
          %th Title
          %th File Name (toggle #{ link_to 'full path', 'Javascript: void(0);', class: 'name_toggle'} )
          %th File Type
      %tbody
        - @books.each do |book|
          %tr{class: book.id}
            %td= check_box_tag "book_ids[]", book.id, default: true
            %td= best_in_place book, :author, :data => { field: book.author }
            %td= best_in_place book, :title, :data => { field: book.title }
            %td.path{:data => { fullpath: book.fullpath }}= book.partial_path
            %td= book.file_type
    = submit_tag "These Look Good", class: 'btn'
  = paginate @books

:javascript
  $('.table-fixed-header').fixedHeader({topOffset: 0})

app/views/books/create.html.haml
%h1 Books#create
%p Find me in app/views/books/create.html.haml

app/views/books/destroy.html.haml
%h1 Books#destroy
%p Find me in app/views/books/destroy.html.haml

app/views/books/edit.html.haml
%h1 Books#edit
%p Find me in app/views/books/edit.html.haml

app/views/books/index.html.haml
%h1 Welcome Ben!
= form_tag books_path, method: :get do
  %div.input-append
    = text_field_tag :query, params[:query], class: 'span4'
    = submit_tag "Search", class: 'btn', name: nil
%p You have #{@book_count} books in the library.
%p Of those #{@book_count} books, #{@books_without_authors} have no author, and #{@books_without_titles} have no titles.
- if @books_without_titles.to_i > 0
  .progress.progress-striped
    .bar{:style => "width: #{ '%.2f' % (( 1.00 - (@books_without_titles.to_f/@book_count.to_f) )* 100)  }%;"}
- if @last_updated_book
  %p 
    The last book you fixed was 
    %strong #{@last_updated_book.title} 
    by 
    %strong #{@last_updated_book.author}.
= link_to 'Get cracking!', Book.no_title.first
%h2 Books!
- @books.each do |book|
  = render book, :fields => book.best_guess_fields

= paginate @books

app/views/books/new.html.haml
%h1 Books#new
%p Find me in app/views/books/new.html.haml

app/views/books/review.html.haml
%h1 Welcome Ben!
- if @books.empty?
  Congratulations, you have no books to review!
  = form_tag runcheck_books_path, method: :get do
    = submit_tag "Run Check", class: 'btn', name: nil
- else
  You have #{@book_count} to review.
  %h2 Books!
  = link_to 'regular view', review_books_path
  |
  = link_to 'bulk view', { layout: 'bulk'}
  - @books.each do |book|
    = render book, :fields => book.best_guess_fields
  = paginate @books

app/views/books/show.html.haml
= render @book, :fields => @fields
%ul.pager
  - if @book.previous
    %li.previous
      = link_to '&larr; previous book'.html_safe, @book.previous
  - if @book.next
    %li.next
      = link_to 'next book &rarr;'.html_safe, @book.next

app/views/books/update.html.haml
%h1 Books#update
%p Find me in app/views/books/update.html.haml

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
= link_to "Ebook Renamer", root_path, :class => 'brand'
%ul.nav
  %li
    = link_to review_books_path layout: 'bulk' do
      %span.badge.badge-info= Book.to_review.count
      Review
  %li
    = link_to 'Cleaned Books', books_path( status: 'cleaned')

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "Ebook Renamer"
      %meta{:content => content_for?(:description) ? yield(:description) : "Ebook Renamer", :name => "description"}
        = stylesheet_link_tag "application", :media => "all"
        = javascript_include_tag "application"
        = csrf_meta_tags
        = yield(:head)
  %body{:class => "#{controller_name} #{action_name}"}
    .navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .row
          .span12
            = render 'layouts/messages'
            = yield
        %footer
      / ! end of .container
    / ! end of #main